name: Security Check
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    name: Image Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.0
          - 8.1
          - 8.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: friendsofshopware/production-docker-base:${{ matrix.php-verison}}
          dockerfile: ./${{ matrix.php-verison}}/Dockerfile

      - name: Upload SARIF file
        if: ${{ steps.scan.outputs.sarif != '' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
